In [41]:
import numpy as np
import pandas as pd

class Instancia():
    def __init__(self,csvfile):
        self._equipos=0
        self._partidos=0
        self._cmm = None
        self.mass=None
        self.diferencia=None
        self.ganados = None
        self.totales = None
        f = open(csvfile, "r")
        i=0
        for line in list(f):
            if i == 0: # header
                i+=1
                columns = line.split()
                self._equipos = int(columns[0])
                self._partidos = int(columns[1])
                self._cmm = np.empty([self._equipos,self._equipos])
                self.ganados= np.empty([self._equipos,self._equipos])
                self.totales = np.zeros(self._equipos)
                self.diferencias = np.zeros(self._equipos)
                for i in range(0,self._equipos):
                    for j in range(0,self._equipos):
                        self.ganados[i,j]=0.0
            else:
                data = line.split();
                print(data)
#                     set_trace()
                self.totales[int(data[1])-1]+=1
                self.totales[int(data[3])-1]+=1
                self.diferencias[int(data[1])-1]+=int(data[2])

                self.diferencias[int(data[1])-1]-=int(data[4])


                self.diferencias[int(data[3])-1]+=int(data[4])

                self.diferencias[int(data[3])-1]-=int(data[2])

                if(int(data[2])>int(data[4])):
                    self.ganados[int(data[1])-1,int(data[3])-1] +=1
                else:
                    self.ganados[int(data[3])-1,int(data[1])-1] +=1
                    
    def equipos(self):
        return self._equipos
    def partidos(self):
        return self._partidos
    def cmm(self):
        return self._cmm
    def wp(self):
        wp = np.zeros(self._equipos)
        for i in range(0,self._equipos):
            wp[i]=sum(self.ganados[i])/self.totales[i]
        
        return wp
import math


def forward_elimination(A, b, n):
    """
    Calculates the forward part of Gaussian elimination.
    """
    for row in range(0, n-1):
        for i in range(row+1, n):
            factor = A[i,row] / A[row,row]
            for j in range(row, n):
                A[i,j] = A[i,j] - factor * A[row,j]

            b[i] = b[i] - factor * b[row]

        print('A = \n%s and b = %s' % (A,b))
    return A, b

def back_substitution(a, b, n):
    """"
    Does back substitution, returns the Gauss result.
    """
    x = np.zeros((n,1))
    x[n-1] = b[n-1] / a[n-1, n-1]
    for row in range(n-2, -1, -1):
        sums = b[row]
        for j in range(row+1, n):
            sums = sums - a[row,j] * x[j]
        x[row] = sums / a[row,row]
    return x

def gauss(A, b):
    """
    This function performs Gauss elimination without pivoting.
    """
    n = A.shape[0]

    # Check for zero diagonal elements
    if any(np.diag(A)==0):
        raise ZeroDivisionError(('Division by zero will occur; '
                                  'pivoting currently not supported'))
    
    A, b = forward_elimination(A, b, n)
    return back_substitution(A, b, n)

In [42]:
ins = Instancia("tests/test1.in")

['1', '1', '16', '4', '13']
['1', '2', '38', '5', '17']
['1', '2', '0', '6', '1']
['1', '3', '34', '1', '21']
['1', '3', '23', '4', '10']
['1', '4', '31', '1', '6']
['1', '5', '0', '6', '1']
['1', '5', '38', '4', '23']
['1', '6', '1', '2', '0']
['1', '6', '1', '5', '0']
['1', '4', '1', '6', '0']
['1', '3', '1', '1', '0']
['1', '3', '1', '2', '0']


In [48]:
ins.partidos()

13

In [53]:
ins.totales

array([4., 4., 4., 5., 4., 5.])

In [52]:
ins.ganados

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [2., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 2., 0., 0., 2., 0.]])

In [40]:
for i in range(0, ins.equipos()):
    for j in range(0, ins.equipos()):
        if i==j:
            ins._cmm[i][j]=  ins.totales[i]+ 2
        else:
            ins._cmm[i][j]=  (ins.ganados[i][j]+ ins.ganados[j][i])*-1

In [41]:
ins._cmm

array([[ 5., -0., -1., -2., -0., -0.],
       [-0.,  5., -0., -0., -1., -2.],
       [-1., -0.,  4., -1., -0., -0.],
       [-2., -0., -1.,  7., -1., -1.],
       [-0., -1., -0., -1.,  6., -2.],
       [-0., -2., -0., -1., -2.,  7.]])

In [42]:
b = np.zeros(ins.equipos())

In [47]:
for i in range(0,ins.equipos()):
    ganados =0
    for j in range(0,ins.equipos()):
        ganados += ins.ganados[i][j]
    b[i]= 1+(2*ganados-ins.totales[i])/2

In [49]:
ins.wp()

array([0.25, 0.25, 1.  , 0.4 , 0.25, 0.8 ])

In [51]:
1/13

0.07692307692307693